# this file is autogenerated by .github/workflows/update.yml
{
  description = "nix-index database";
  outputs = _:
    {
      legacyPackages.x86_64-linux.database = builtins.fetchurl {
        url = "https://github.com/badele/fork-nix-index-database/releases/download/2023-03-12/index-x86_64-linux";
        sha256 = "1azgbcjgppcdahpdj77p4qmcd587vdh7ngg7lqz7nsakbp7y9krd";
      };
      legacyPackages.x86_64-darwin.database = builtins.fetchurl {
        url = "https://github.com/badele/fork-nix-index-database/releases/download/2023-03-12/index-x86_64-darwin";
        sha256 = "1wq1rxxgpfsz4fxvngbsc7vd8lq5zhywi43ww9aqbza4bk299xax";
      };
      legacyPackages.aarch64-linux.database = builtins.fetchurl {
        url = "https://github.com/badele/fork-nix-index-database/releases/download/2023-03-12/index-aarch64-linux";
        sha256 = "19l5nzjb9hb4jqg2j8v64d615pyihqjma6fb4xjrkyaqxfm9lin7";
      };
    };
}
