# this file is autogenerated by .github/workflows/update.yml
{
  description = "nix-index database";
  outputs = _:
    {
      legacyPackages.x86_64-linux.database = builtins.fetchurl {
        url = "https://github.com/badele/fork-nix-index-database/releases/download/2022-11-06/index-x86_64-linux";
        sha256 = "137knk91spd2saii2lgyyrp5y0xzyn32y61slhigkqhh02qybna0";
      };
      legacyPackages.x86_64-darwin.database = builtins.fetchurl {
        url = "https://github.com/badele/fork-nix-index-database/releases/download/2022-11-06/index-x86_64-darwin";
        sha256 = "0nbgw2j8ka2rih89kx8dpzrvxy46ybzxir3vdncv5y1dznly31v9";
      };
      legacyPackages.aarch64-linux.database = builtins.fetchurl {
        url = "https://github.com/badele/fork-nix-index-database/releases/download/2022-11-06/index-aarch64-linux";
        sha256 = "1i0lc6jk8fqvmzh180b5ahd61dixn5hifdsqanr5841xhxqn1wp7";
      };
    };
}
